---
title: "ARABM"
author: "Yang Xiao"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(bayesplot)
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "functions", "tidy_dengueBR.R"))


path_source_nowcasting <- "/Users/xiaoy0a/Desktop/GitHub/Dengue/nowcasting/source"
source(file.path(path_source_nowcasting, "simulation", "simulations_functions_final.R"))
source(file.path(path_source_nowcasting, "functions", "prior_function.R"))
source(file.path(path_source_nowcasting, "functions", "fit_function.R"))
source(file.path(path_source_nowcasting, "functions", "plot_function.R"))

error_metrics <- function(predicted, actual) {
  # same length
  stopifnot(length(predicted) == length(actual))
  
  # RMSE (Root Mean Squared Error)
  rmse <- sqrt(mean((predicted - actual)^2))
  
  # RMSPE (Root Mean Squared Percentage Error)
  rmspe <- sqrt(mean(((predicted - actual)/actual)^2)) * 100
  
  # MAE (Mean Absolute Error)
  mae <- mean(abs(predicted - actual))
  
  # MAPE (Mean Absolute Percentage Error)
  mape <- mean(abs((predicted - actual)/actual)) * 100

  list(RMSE = rmse,
       RMSPE = rmspe,
       MAE = mae,
       MAPE = mape)
}
```


```{r}
start_week <- 202410
end_week <- 202433
start_date <- get_date(week = substr(start_week,5,6), year = substr(start_week,1,4))
end_date <- get_date(week = substr(end_week,5,6), year = substr(end_week,1,4))

data_root_dir <- "/Users/xiaoy0a/Desktop/GitHub/Dengue/dengue-tracker/data/weekly_data/infodengue"
# Input matrix of BRdengue, SP state
rj_delay_matrix <- get_infodengue_data(root_dir = data_root_dir,
                         start_week, end_week, "RJ",
                         D = 15)$RJ
rj_delay_matrix[15,1] <- round(rj_delay_matrix[15,2]/2)

matplot(t(log(rj_delay_matrix)), type = "l", lty = 1, col = rainbow(nrow(rj_delay_matrix)))
```

```{r}
rj_ref_data_root <- file.path(data_root_dir, "202511", "RJ_2025-03-16_infodengue.csv")
rj_ref_data <- read.csv(rj_ref_data_root)
# we start from 202410
rj_actual_cases <- rj_ref_data %>% filter(ew >= start_week & ew <= end_week) %>%
  select(ew_start, ew, sum_of_cases)
```

```{r}
# checking the value of b
page_num <- ceiling(nrow(na.omit(rj_delay_matrix))/16)
exp_plot_rj <- fit_exp_plot(na.omit(rj_delay_matrix), ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
exp_plot_rj
exp_plot_rj$coefficients

smoothed_b_rj <- data.frame( date = as.Date(rownames(na.omit(rj_delay_matrix))),
                          b = exp_plot_rj$coefficients$b)

ggplot(smoothed_b_rj, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +
  geom_smooth(method = "loess", se = TRUE,
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")
```

```{r}
ind = end_week - start_week + 1
test_length <- 10 #8 weeks
hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
rj_delay_matrix[is.na(rj_delay_matrix)] <- 0
stan_data <- c(list(T = ind, D = 15, Y = rj_delay_matrix), hypers)

b_ou <- file.path(path_source_nowcasting, "models", "b-ou.stan")
model <- cmdstan_model(b_ou)
test_ARABM = model$sample(
    data = stan_data,
    iter_sampling = 10000,
    iter_warmup = 5000,
    chains = 3,
    parallel_chains = 3,
    refresh = 0,
    thin = 1)
varnames_ARABM <- test_ARABM$summary()$variable

mcmc_areas(test_ARABM$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABM$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABM$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABM$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_ARABM$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABM$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames_ARABM, value = TRUE),
    x = rj_actual_cases$sum_of_cases[1:ind]
)
mcmc_areas(test_ARABM$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

mean_N_ARABM <- test_ARABM$summary(variables = c("N"))$mean


error_metrics(tail(mean_N_ARABM, test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))
```

```{r}
test_length <- 5
error_metrics(tail(mean_N_ARABM, test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))

error_metrics(mean_N_ARABM, 
     rj_actual_cases$sum_of_cases)
```
```{r}
error_metrics <- function(pred, actual) {
  rmse <- sqrt(mean((pred - actual)^2, na.rm = TRUE))
  rmspe <- sqrt(mean(((pred - actual) / actual)^2, na.rm = TRUE)) * 100
  mae <- mean(abs(pred - actual), na.rm = TRUE)
  mape <- mean(abs((pred - actual) / actual), na.rm = TRUE) * 100
  
  list(
    RMSE = rmse,
    RMSPE = rmspe,
    MAE = mae,
    MAPE = mape
  )
}
```

