---
title: "ARABM"
author: "Yang Xiao"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(bayesplot)
library(aweek)
library(dplyr)
library(ggplot2)
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "functions", "tidy_dengueBR.R"))

path_source_nowcasting <- "/Users/xiaoy0a/Desktop/GitHub/Dengue/nowcasting/source"
source(file.path(path_source_nowcasting, "simulation", "simulations_functions_final.R"))
source(file.path(path_source_nowcasting, "functions", "prior_function.R"))
source(file.path(path_source_nowcasting, "functions", "fit_function.R"))
source(file.path(path_source_nowcasting, "functions", "plot_function.R"))

```




```{r}
state <- "RJ"
D <- 15

# time period to control the triangular period
start_week <- 202410
end_week <- 202433
start_date <- get_date(week = substr(start_week,5,6), year = substr(start_week,1,4))
end_date <- get_date(week = substr(end_week,5,6), year = substr(end_week,1,4))

data_root_dir <- "/Users/xiaoy0a/Desktop/GitHub/Dengue/dengue-tracker/data/weekly_data/infodengue"
# Input matrix of BRdengue, SP state
rj_delay_matrix <- get_infodengue_data(root_dir = data_root_dir,
                         start_week, end_week, state, D = 15)$RJ
rj_delay_matrix[15,1] <- round(rj_delay_matrix[15,2]/2)
# rj_delay_matrix_scaled <- log_minmax_scale_df(rj_delay_matrix)

matplot(t(log(rj_delay_matrix)), type = "l", lty = 1, col = rainbow(nrow(rj_delay_matrix)))


# historical
k = 3 # smooth para
ealiest_date <- start_date - years(2) 
ealiest_date_for_smooth <- ealiest_date - weeks(k-1)

hist_case <- readr::read_csv(file.path(path_source_denguetracker_infodengue,202519, 
                                            paste0(state,"_2025-05-11_infodengue.csv")), show_col_types = FALSE) %>%
  filter(ew_start >= ealiest_date & ew_start <= end_date - weeks(ind)) %>%
  select(sum_of_cases) 

```

```{r}
t <- 1:as.numeric(ceiling((end_date - ealiest_date + 1)/7))
P <- 52; H_max <- 10
H_used <- 4

angle <- 2 * pi * (t - 1) / P  # for each t we have one angle
fourier_list <- lapply(1:H_max, function(h) {
  cbind(
    cos_h = cos(h * angle),
    sin_h = sin(h * angle)
  )
})
fourier_basis <- do.call(cbind, fourier_list)
# column name
colnames(fourier_basis) <- unlist(lapply(1:H_max, function(h) {
  c(paste0("cos_h", h), paste0("sin_h", h))
}))
```

```{r}
rj_ref_data_root <- file.path(data_root_dir, "202511", "RJ_2025-03-16_infodengue.csv")
rj_ref_data <- read.csv(rj_ref_data_root)
# we start from 202410
rj_actual_cases <- rj_ref_data %>% filter(ew_start >= ealiest_date & ew <= end_week) %>%
  select(ew_start, ew, sum_of_cases)
```



```{r}
gt = read.csv("/Users/xiaoy0a/Desktop/GitHub/Dengue/dengue-tracker/data/weekly_data/gtrends/202452/RJ_trends.csv", stringsAsFactors = FALSE, skip = 2)[,c(1:2)]
names(gt) <- c("date", "dengue")

gt_temp <- gt %>% filter(date <= end_date & date >= ealiest_date_for_smooth)
gt_smooth <- zoo::rollmean(gt_temp$dengue, k = k, align = "right")



# gt_smooth <- apply(gt_smooth, function(x) {
#   as.numeric(ifelse(x == "<1", 0.5, x))
# })

covars_matrix <- as.matrix(gt_smooth_central)

```


```{r}
weeks_per_yr <- 52
n_weeks <- 24
ind = as.numeric(ceiling((end_date - start_date + 1)/7))
E = 10000

hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
rj_delay_matrix[is.na(rj_delay_matrix)] <- 0
stan_data <- c(list(H = 104, T = ind, D = 15, 
                    Y = rj_delay_matrix, C_hist = hist_case$sum_of_cases),
               hypers,
               list(K = 1, x = matrix(covars_matrix[,1]), E = E),
               list(S = H_used*2,  
                bases_s = fourier_basis[,1:(H_used*2)])
               )

b_ou_GT <- file.path(path_source, "models", "nowcast_hist_triangle.stan")
model <- cmdstan_model(b_ou_GT)
test_ARABMwGT = model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 500,
    thin = 1)
varnames_ARABMwGT <- test_ARABMwGT$summary()$variable

mcmc_areas(test_ARABMwGT$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABMwGT$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABMwGT$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABMwGT$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_ARABMwGT$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_ARABMwGT$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true = tibble(
    parameter = grep("^N_rep\\[.+\\]$", varnames_ARABMwGT, value = TRUE),
    x = rj_actual_cases$sum_of_cases[1:ind]
)
mcmc_areas(test_ARABMwGT$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

mean_N_ARABMwGT <- test_ARABMwGT$summary(variables = c("N_rep"))$mean

```


```{r}
test_length <- 5

error_metrics(tail(mean_N_ARABMwGT, test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))

error_metrics(mean_N_ARABMwGT, 
     rj_actual_cases$sum_of_cases)
```
```{r}
plot(ts(scale(log(rj_actual_cases$sum_of_cases))))
lines(ts(scale(log(covars_matrix[,1]))), col = "red")
```

```{r}
plot(ts(scale(log(covars_matrix[,1]))))

```
```{r}

stan_data_scaled <- c(list(T = ind, D = 15, Y = rj_delay_matrix_scaled, 
                     K = 1, X = log_minmax_scale_df(covars_matrix[,1])), hypers)

b_ou_GT_scaled <- file.path(path_source, "models", "b-ou-GT-transform.stan")
model <- cmdstan_model(b_ou_GT_scaled)
test_ARABMwGT_trans = model$sample(
    data = stan_data_scaled,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 500,
    thin = 1)

varnames_ARABMwGT_trans <- test_ARABMwGT_trans$summary()$variable

param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames_ARABMwGT_trans, value = TRUE),
    x = as.vector(log_minmax_scale_df( rj_actual_cases$sum_of_cases[1:ind]))[[1]]
)


mcmc_areas(varnames_ARABMwGT_trans$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

mean_N_ARABMwGT <- varnames_ARABMwGT_trans$summary(variables = c("N"))$mean
varnames_ARABMwGT_trans
error_metrics(tail(mean_N_ARABMwGT, test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))

```

