---
title: "LwGT"
author: "Yang Xiao"
date: "2025-03-26"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(bayesplot)
```

# Environment
```{r}

path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "functions", "dengue_tracker_functions.R"))
source(file.path(path_source, "functions", "tidy_dengueBR.R"))
source(file.path(path_source, "functions", "fit_function.R"))
aweek::set_week_start("Sunday")

path_source_nowcasting <- file.path(dirname(path_proj), "nowcasting", "source")
source(file.path(path_source_nowcasting, "simulation", "simulations_functions_final.R"))
source(file.path(path_source_nowcasting, "functions", "prior_function.R"))
source(file.path(path_source_nowcasting, "functions", "fit_function.R"))
source(file.path(path_source_nowcasting, "functions", "plot_function.R"))

path_source_denguetracker_data <- file.path(dirname(path_proj), "dengue-tracker/data/weekly_data/")
path_source_denguetracker_infodengue <- file.path(path_source_denguetracker_data, "infodengue")
path_source_denguetracker_GT <- file.path(path_source_denguetracker_data, "gtrends")
```
# Parameter settings
```{r}
delay_D <- 15
iter_sampling <- 5000
iter_warmup <- 2000
window_length <- 10
thin <- 2
step_size <- 2
chain_num <- 1
 
ew_start <- "202410"
ew_end <- "202436"

state <- "RJ"
```

# Fourier basis
```{r}
generate_fourier_basis <- function(weeks, H_max = 3, period = 52) {
  if (inherits(weeks, "Date")) {
    weeks <- seq_along(weeks)
  }

  angle <- 2 * pi * (weeks - 1) / period

  fourier_list <- lapply(1:H_max, function(h) {
    cbind(
      cos = cos(h * angle),
      sin = sin(h * angle)
    )
  })

  basis <- do.call(cbind, fourier_list)

  # colnames
  colnames(basis) <- unlist(lapply(1:H_max, function(h) {
    c(paste0("cos_h", h), paste0("sin_h", h))
  }))

  return(basis)
}

weeks_per_yr <- 52
t <- 1:(weeks_per_yr * 3)
fourier_basis <- generate_fourier_basis(t, H_max = 10, period = weeks_per_yr)
H_used <- 3
```


```{r}
error_metrics <- function(predicted, actual) {
  # same length
  stopifnot(length(predicted) == length(actual))
  
  # RMSE (Root Mean Squared Error)
  rmse <- sqrt(mean((predicted - actual)^2))
  
  # RMSPE (Root Mean Squared Percentage Error)
  rmspe <- sqrt(mean(((predicted - actual)/actual)^2)) * 100
  
  # MAE (Mean Absolute Error)
  mae <- mean(abs(predicted - actual))
  
  # MAPE (Mean Absolute Percentage Error)
  mape <- mean(abs((predicted - actual)/actual)) * 100

  list(RMSE = rmse,
       RMSPE = rmspe,
       MAE = mae,
       MAPE = mape)
}

```

```{r, warning=FALSE}
baseline <- get_baseline_data(
  root_dir = path_source_denguetracker_data, # root file for data,
  states = state,
  start = ew_start,
  end = ew_end,
  time_unit = "week",
  last_n = 10
)

baseline <- add_actual_cases(baseline, 
                               root_dir_infodengue = path_source_denguetracker_infodengue,
                               state,
                               202511)

```

# Fixed window: window length = 8
```{r}
results <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = state,
  full_start = ew_start,
  full_end = ew_end,
  #window_length = 8,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source_nowcasting, "models", "b-ou.stan"),
  model_name = "ARABM",
  mode = "expanding",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = chain_num,
  posterior_draws_path = file.path(path_proj, "draws", "length8")
)

results_wGT <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = state,
  full_start = ew_start, 
  full_end = ew_end,
  #window_length = 8,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  E =10000,
  S = H_used *2,
  bases_s = fourier_basis[, 1:(H_used*2)],
  model_file = file.path(path_source, "models", "nowcast_hist_triangle.stan"),
  model_name = "ARABMwGT",
  mode = "expanding",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = chain_num,
  posterior_draws_path = file.path(path_proj, "draws", "length8")
)

arabm <- extract_N_summary(results, num_N = 6)
arabm_wGT <- extract_N_summary(results_wGT, num_N = 6, model_name = "ARABMwGT")

print("done")
```

```{r}
result_out <- baseline %>%
  left_join(
    arabm %>% select(ew_now, ew, ARABM, ARABM_lwr, ARABM_upr),
    by = c("ew_now", "ew")
  ) %>%
  left_join(
    arabm_wGT %>% select(ew_now, ew, ARABMwGT, ARABMwGT_lwr, ARABMwGT_upr),
    by = c("ew_now", "ew")
  ) 

# result_out <- add_actual_cases(result_out, 
#                                root_dir_infodengue = path_source_denguetracker_infodengue,
#                                state,
#                                202511) 
n_last <- 4

result_out_cut <- result_out %>%
  filter(!is.na(ARABM)) %>%
  group_by(ew_now) %>%
  slice_max(order_by = ew, n = n_last) %>%  
  ungroup()

result_out_cut

Bastos_metrics <- error_metrics(result_out_cut$cases_est_id, result_out_cut$sum_of_cases_final)
GT_metrics <- error_metrics(result_out_cut$GT, result_out_cut$sum_of_cases_final)
ARABM_metrics <- error_metrics(result_out_cut$ARABM, result_out_cut$sum_of_cases_final)
ARABMwGT_metrics <- error_metrics(result_out_cut$ARABMwGT, result_out_cut$sum_of_cases_final)

Bastos_metrics
GT_metrics 
ARABM_metrics
ARABMwGT_metrics



```

```{r}
num_tail <-3


Bastos_metrics <- error_metrics(tail(result_out_cut$cases_est_id,num_tail), 
                                tail(result_out_cut$sum_of_cases_final,num_tail))
GT_metrics <- error_metrics(tail(result_out_cut$GT,num_tail),
                            tail(result_out_cut$sum_of_cases_final,num_tail))
ARABM_metrics <- error_metrics(tail(result_out_cut$ARABM, num_tail),
                               tail(result_out_cut$sum_of_cases_final,num_tail))
ARABMwGT_metrics <- error_metrics(tail(result_out_cut$ARABMwGT, num_tail),
                                  tail(result_out_cut$sum_of_cases_final,num_tail))

Bastos_metrics
GT_metrics 
ARABM_metrics
ARABMwGT_metrics
```
```{r}
num_head <- 4


Bastos_metrics <- error_metrics(head(result_out_cut$cases_est_id,num_head), 
                                head(result_out_cut$sum_of_cases_final,num_head))
GT_metrics <- error_metrics(head(result_out_cut$GT,num_head),
                            head(result_out_cut$sum_of_cases_final,num_head))
ARABM_metrics <- error_metrics(head(result_out_cut$ARABM, num_head),
                               head(result_out_cut$sum_of_cases_final,num_head))
ARABMwGT_metrics <- error_metrics(head(result_out_cut$ARABMwGT, num_head),
                                  head(result_out_cut$sum_of_cases_final,num_head))

Bastos_metrics
GT_metrics 
ARABM_metrics
ARABMwGT_metrics
```

```{r}
result_out_cut$sum_of_cases_final
```

# Fixed window: window length = 6
```{r}
results_length6 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = "RJ",
  full_start = ew_start,
  full_end = ew_end,
  window_length = 6,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source_nowcasting, "models", "b-ou.stan"),
  model_name = "ARABM",
  mode = "fixed",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length6")
)

results_wGT_length6 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = "RJ",
  full_start = ew_start, 
  full_end = ew_end,
  window_length = 6,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source, "models", "b-ou-GT.stan"),
  model_name = "ARABMwGT",
  mode = "fixed",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length6")
)

arabm_length6 <- extract_N_summary(results_length6, num_N = 1)
arabm_wGT_length6 <- extract_N_summary(results_wGT_length6, num_N = 1, model_name = "ARABMwGT")

```

```{r}
result_out_length6 <- baseline %>%
  left_join(
    arabm_length6 %>% select(ew_now, ew, ARABM, ARABM_lwr, ARABM_upr),
    by = c("ew_now", "ew")
  ) %>%
  left_join(
    arabm_wGT_length6 %>% select(ew_now, ew, ARABMwGT, ARABMwGT_lwr, ARABMwGT_upr),
    by = c("ew_now", "ew")
  ) 

result_out_length6 <- add_actual_cases(result_out_length6, 
                               root_dir_infodengue = path_source_denguetracker_infodengue,
                               "RJ",
                               202511)
result_out_length6 <- result_out_length6 %>%
  filter(!is.na(ARABM))



Bastos_metrics_length6 <- error_metrics(result_out_length6$cases_est_id, result_out_length6$sum_of_cases_final)
GT_metrics_length6 <- error_metrics(result_out_length6$GT, result_out_length6$sum_of_cases_final)
ARABM_metrics_length6 <- error_metrics(result_out_length6$ARABM, result_out_length6$sum_of_cases_final)
ARABMwGT_metrics_length6 <- error_metrics(result_out_length6$ARABMwGT, result_out_length6$sum_of_cases_final)

Bastos_metrics_length6
GT_metrics_length6 
ARABM_metrics_length6
ARABMwGT_metrics_length6

```


# Fixed window: window length = 5
```{r}
results_length5 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = c("RJ","AC"),
  full_start = ew_start,
  full_end = ew_end,
  window_length = 5,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source_nowcasting, "models", "b-ou.stan"),
  model_name = "ARABM",
  mode = "fixed",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length5")
)

results_wGT_length5 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = c("RJ","AC"),,
  full_start = ew_start, 
  full_end = ew_end,
  window_length = 5,
  step_size = step_size,
  D = delay_D,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source, "models", "b-ou-GT.stan"),
  model_name = "ARABMwGT",
  mode = "fixed",
  iter_sampling = iter_sampling,
  iter_warmup = iter_warmup,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length5")
)

arabm_length5 <- extract_N_summary(results_length5, num_N = 1)
arabm_wGT_length5 <- extract_N_summary(results_wGT_length5, num_N = 1, model_name = "ARABMwGT")

```

```{r}
result_out_length5 <- baseline %>%
  left_join(
    arabm_length5 %>% select(ew_now, ew, ARABM, ARABM_lwr, ARABM_upr),
    by = c("ew_now", "ew")
  ) %>%
  left_join(
    arabm_wGT_length5 %>% select(ew_now, ew, ARABMwGT, ARABMwGT_lwr, ARABMwGT_upr),
    by = c("ew_now", "ew")
  ) 

result_out_length5 <- add_actual_cases(result_out_length5, 
                               root_dir_infodengue = path_source_denguetracker_infodengue,
                               "RJ",
                               202511)
result_out_length5 <- result_out_length5 %>%
  filter(!is.na(ARABM))



Bastos_metrics_length5 <- error_metrics(result_out_length5$cases_est_id, result_out_length5$sum_of_cases_final)
GT_metrics_length5 <- error_metrics(result_out_length5$GT, result_out_length5$sum_of_cases_final)
ARABM_metrics_length5 <- error_metrics(result_out_length5$ARABM, result_out_length5$sum_of_cases_final)
ARABMwGT_metrics_length5 <- error_metrics(result_out_length5$ARABMwGT, result_out_length5$sum_of_cases_final)

Bastos_metrics_length5
GT_metrics_length5 
ARABM_metrics_length5
ARABMwGT_metrics_length5

```

# Fixed window: window length = 4
```{r}
results_length4 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = "RJ",
  full_start = ew_start,
  full_end = ew_end,
  window_length = 4,
  step_size = step_size,
  D = 15,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source_nowcasting, "models", "b-ou.stan"),
  model_name = "ARABM",
  mode = "fixed",
  iter_sampling = 2000,
  iter_warmup = 500,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length4")
)

results_wGT_length4 <- run_moving_window(
  root_dir_infodengue = path_source_denguetracker_infodengue,
  root_dir_GT = path_source_denguetracker_GT,
  state = "RJ",
  full_start = ew_start, 
  full_end = ew_end,
  window_length = 4,
  step_size = step_size,
  D = 15,
  hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential",
                    alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15),
  model_file = file.path(path_source, "models", "b-ou-GT.stan"),
  model_name = "ARABMwGT",
  mode = "fixed",
  iter_sampling = 2000,
  iter_warmup = 500,
  chains = 3,
  posterior_draws_path = file.path(path_proj, "draws", "length4")
)

arabm_length4 <- extract_N_summary(results_length4, num_N = 1)
arabm_wGT_length4 <- extract_N_summary(results_wGT_length4, num_N = 1, model_name = "ARABMwGT")

```

```{r}
result_out_length4 <- baseline %>%
  left_join(
    arabm_length4 %>% select(ew_now, ew, ARABM, ARABM_lwr, ARABM_upr),
    by = c("ew_now", "ew")
  ) %>%
  left_join(
    arabm_wGT_length4 %>% select(ew_now, ew, ARABMwGT, ARABMwGT_lwr, ARABMwGT_upr),
    by = c("ew_now", "ew")
  ) 

result_out_length4 <- add_actual_cases(result_out_length4, 
                               root_dir_infodengue = path_source_denguetracker_infodengue,
                               "RJ",
                               202511)
result_out_length4 <- result_out_length4 %>%
  filter(!is.na(ARABM))



Bastos_metrics_length4 <- error_metrics(result_out_length4$cases_est_id, result_out_length4$sum_of_cases_final)
GT_metrics_length4 <- error_metrics(result_out_length4$GT, result_out_length4$sum_of_cases_final)
ARABM_metrics_length4 <- error_metrics(result_out_length4$ARABM, result_out_length4$sum_of_cases_final)
ARABMwGT_metrics_length4 <- error_metrics(result_out_length4$ARABMwGT, result_out_length4$sum_of_cases_final)

Bastos_metrics_length4
GT_metrics_length4 
ARABM_metrics_length4
ARABMwGT_metrics_length4

```

```{r}
save(out_b_constant_FR_multi, file = file.path(data_save_path, "FR_b_constant_multi.RData"))
```

