---
title: "LwGT"
author: "Yang Xiao"
date: "2025-03-26"
output: html_document
---

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")


path_source_denguetracker <- path_proj
source(file.path(path_source, "functions", "dengue_tracker_functions.R"))
aweek::set_week_start("Sunday")
```

```{r}
error_metrics <- function(predicted, actual) {
  # same length
  stopifnot(length(predicted) == length(actual))
  
  # RMSE (Root Mean Squared Error)
  rmse <- sqrt(mean((predicted - actual)^2))
  
  # RMSPE (Root Mean Squared Percentage Error)
  rmspe <- sqrt(mean(((predicted - actual)/actual)^2)) * 100
  
  # MAE (Mean Absolute Error)
  mae <- mean(abs(predicted - actual))
  
  # MAPE (Mean Absolute Percentage Error)
  mape <- mean(abs((predicted - actual)/actual)) * 100

  list(RMSE = rmse,
       RMSPE = rmspe,
       MAE = mae,
       MAPE = mape)
}

ind = 202452 - 202410 + 1 + 2
test_length <- 8 #8 weeks
test_gt <- tail(generate_data("RJ", last_ew_start = as.Date("2024-12-29"), ew = 202452, save=F), ind) 
as.numeric(head(test_gt$prediction, ind - 2)) # keep the last 43 but the very last one is removed

rj_actual_cases$sum_of_cases - as.numeric(head(test_gt$prediction, ind - 2)) 

error_metrics(tail(as.numeric(head(test_gt$prediction, ind - 2)), test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))
```
```{r}
bastos_Bayesian <- head(tail(generate_data("RJ", last_ew_start = as.Date("2024-12-29"), ew = 202452, save=F) , ind), ind - 2)


error_metrics(tail(bastos_Bayesian$cases_est_id, test_length), 
     tail(rj_actual_cases$sum_of_cases,test_length))
```

