---
title: "Time-varying parametric reported probability: OU process"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
library(bayesplot)
library(scoringRules)
```

```{r}
path_proj = here::here()
path_source_nowcasting <- file.path(dirname(path_proj), "nowcasting", "source")

source(file.path(path_source_nowcasting, "simulation", "simulations_functions_final.R"))
source(file.path(path_source_nowcasting, "functions", "prior_function.R"))
posterior_draws_path = file.path(path_source_nowcasting, "data", "draws", "testEach")

source(file.path(path_proj, "source", "functions", "simulation_functions.R"))

error_metrics <- function(predicted, actual) {
  # same length
  stopifnot(length(predicted) == length(actual))
  
  # RMSE (Root Mean Squared Error)
  rmse <- sqrt(mean((predicted - actual)^2))
  
  # RMSPE (Root Mean Squared Percentage Error)
  rmspe <- sqrt(mean(((predicted - actual)/actual)^2)) * 100
  
  # MAE (Mean Absolute Error)
  mae <- mean(abs(predicted - actual))
  
  # MAPE (Mean Absolute Percentage Error)
  mape <- mean(abs((predicted - actual)/actual)) * 100

  list(RMSE = rmse,
       RMSPE = rmspe,
       MAE = mae,
       MAPE = mape)
}
```

```{r}
b_ou <-  file.path(path_source_nowcasting, "models", "b-ou.stan")
model <- cmdstan_model(b_ou)

#file.path(dirname(dirname(path_proj)),"cmdstan-2.32.0")
#set_cmdstan_path(file.path(dirname(dirname(path_proj)),"cmdstan-2.32.0"))

b_ou_lambda <-  file.path(path_proj, "source", "models", "b-ou-GT-combined-seasonality-fourier-new.stan")
# b_ou_lambda <- file.path(path_proj, "source", "models", "b-ou-GT-time-varying-betas.stan")
model_GT <- cmdstan_model(b_ou_lambda)
```
# GT

```{r}
# --- preliminaries unchanged -------------------------------------------------
#set.seed(111)
years <- 3; weeks_per_yr <- 52; T_len <- years * weeks_per_yr
t     <- seq_len(T_len)
week  <- ((t - 1) %% weeks_per_yr) + 1
E     <- rep(1000, T_len)

# set the total var and ratio
total_var = 0.01

tau_epsilon <- 1
tau_ar <- 1
tau_cov <- 1

sigma_epsilon <- sqrt(total_var * tau_epsilon / (tau_epsilon + tau_ar + tau_cov))
sd_ar <- sqrt(total_var * tau_ar / (tau_epsilon + tau_ar + tau_cov))
beta1 <- sqrt(total_var * tau_cov / (tau_epsilon + tau_ar + tau_cov))

# --- (1) Independent noise ---------------------------------------------------
#sigma_epsilon  <- 0.1
epsilon_t    <- rnorm(T_len, mean = 0, sd = sigma_epsilon)

# --- (2) Dependent noise ---------------------------------------------------
# sigma_epsilon = sqrt((1- rho_w^2) * var_ar)
#sd_ar <- 0.1
rho_w <- 0.8
sigma_w  <- sqrt((1-rho_w^2) * sd_ar^2)
w_t <- arima.sim(model = list(ar = rho_w), n = T_len,
                 sd = sigma_w)

# --- (3) covariate X_t -------------------------------------------------------
#x_t <- scale(rnorm(T_len))[, 1]        # standard normal, independent of other components
x_t <- rnorm(T_len) 
#beta1     <- 0.1
beta0 <- 0.2

# --- (4) seasonality ---------------------------------------------------------
# --- baisc setting ---------------------------------------------------
H_max <- 10            # harmonic
P     <- weeks_per_yr   # periodic

# --- Fourier basis -------------------------------------------------
# to each h，we generate cos(h*angle) and sin(h*angle)
angle <- 2 * pi * (t - 1) / P  # for each t we have one angle
fourier_list <- lapply(1:H_max, function(h) {
  cbind(
    cos_h = cos(h * angle),
    sin_h = sin(h * angle)
  )
})
fourier_basis <- do.call(cbind, fourier_list)
# column name
colnames(fourier_basis) <- unlist(lapply(1:H_max, function(h) {
  c(paste0("cos_h", h), paste0("sin_h", h))
}))
 
# --- coefficient beta_s for seasonality---------------------------------
set.seed(3)
H_used <- 5
ratio  <- c(10, 2, 1, 1, 1) # ratio of each frequency (SD)）  
sigma_s    <- 1.8                # total variance

# —— calc the scaling ratio c ——  
# total "share" of var：
sigma_s_raw <- sum(2 * (ratio^2))  
# scaling ratio：
c     <- sqrt(sigma_s / sigma_s_raw)  

# —— σ_h ——  
sd_h   <- ratio * c           
sd_all <- rep(sd_h, each = 2)  # twice，for each cos_h and sin_h  

# —— generate beta_s and s_t ——  
beta_s <- rnorm(2 * H_used, mean = 0, sd = sd_all)  
s_t    <- as.vector(fourier_basis[, 1:(2*H_used)] %*% beta_s)

log_lambda <- beta0 + beta1 * x_t + s_t + w_t + epsilon_t

lambda_t   <- exp(log_lambda)

mu_t  <- E * lambda_t
N     <- rpois(T_len, mu_t)


par(mfrow = c(2,3))
plot(s_t, type = "l")
plot(w_t, type = "l")
plot(beta1 * x_t, type = "l")
plot(epsilon_t, type = "l")
plot(log_lambda, type = "l")
plot(N, type = "l")

```


## Fully reported scenario

### Setting

```{r}
# data
# alpha_increase_seq_1 <- seq(10, 750, by = 30)
# alpha_decrease_seq_1 <- seq(750, 10, by = -30)
# alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10),
#                  alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
#                  rep(10,5))

# Time_len = 60
#D <- 15;
lambda <- mu_t
D <- 15
```

### Simulation

## Non-fully reported scenario

### Simulation

```{r}
# ou_FR
params_b_ou_FR <- list(
  data = list(
    lambda = lambda,
    T       = T_len,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "b_ou",
    method_params = list(theta_logb = 0.7, mu_logb = log(0.8), init_logb = log(0.8), sigma_logb = 0.4,
                         theta_logitphi = 0.7, mu_logitphi = inverse_logistic_transform(0.2, 0, 1), init_logitphi = inverse_logistic_transform(0.2, 0, 1), sigma_logitphi = 0.15)
  )
)

b_ou_FR <- simulateData(params_b_ou_FR)
par(mfrow = c(2, 1))
plot(b_ou_FR$b, pch = 19, type = "b")
plot(b_ou_FR$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(b_ou_FR$q), type = "l", lty = 1, ylim = c(0, 1))

```

### Model fitting

```{r}
ind = 52
varnames_FR <- list()
vanilla_FR <- list()
test_FR <- list()
hypers = hypers_q(phi_ref = 0.1, D_ref = 25, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
for (i in 1:length(ind)) {
  print(paste0("The ",i,"th simulation."))
  stan_data <- c(list(T = ind[i], D = D, Y = b_ou_FR$case_reported_cumulated[1:ind[i], ]), hypers)
  test_FR[[i]] = model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 0,
    thin = 1)
  varnames_FR[[i]] <- test_FR[[i]]$summary()$variable
  vanilla_FR[[i]] <- test_FR[[i]]$summary(variables = "N")$mean
}

```

```{r}
varnames_GT_FR <- list()
withGT_FR <- list()
test_GT_FR <- list()
hypers = hypers_q(phi_ref = 0.1, D_ref = 25, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
for (i in 1:length(ind)) {
  print(paste0("The ",i,"th simulation."))
  stan_data_GT_FR <- c(list(T = ind[i], D = D, Y = b_ou_FR$case_reported_cumulated[1:ind[i], ]), hypers, 
               list(K = ncol(matrix(x_t)), x = as.matrix(matrix(x_t)[1:ind[i], 1]),
                    S = H_used*2, #ncol(fourier_basis_scaled), 
                    bases_s = fourier_basis[(1:ind[i]),1:(H_used*2)],
                    E = 1000
                    ))
test_GT_FR[[i]] = model_GT$sample(
    data = stan_data_GT_FR,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 500,
    thin = 1)
  varnames_GT_FR[[i]] <- test_GT_FR[[i]]$summary()$variable
  withGT_FR[[i]] <- test_GT_FR[[i]]$summary(variables = "N")$mean
}


```

```{r}
vanilla_FR_combined <- list()
withGT_FR_combined <- list()
for (i in 1:(length(ind))) {
    print(paste0("The ",i,"th simulation."))
  print(error_metrics(vanilla_FR[[i]], b_ou_FR$case_true[1:ind[i]]))
  print(error_metrics(withGT_FR[[i]], b_ou_FR$case_true[1:ind[i]]))
  vanilla_FR_combined[[i]] <- as.data.frame(error_metrics(vanilla_FR[[i]], b_ou_FR$case_true[1:ind[i]]))
  withGT_FR_combined[[i]] <- as.data.frame(error_metrics(withGT_FR[[i]], b_ou_FR$case_true[1:ind[i]]))
}

mean_vanilla_FR_combined <- Reduce(`+`, vanilla_FR_combined) / length(vanilla_FR_combined)
mean_withGT_FR_combined <- Reduce(`+`, withGT_FR_combined) / length(withGT_FR_combined)

mean_vanilla_FR_combined
mean_withGT_FR_combined
```

```{r}
# last 3 weeks
vanilla_FR_combined_last <- list()
withGT_FR_combined_last <- list()
last_len <- 3
for (i in 1:(length(ind))) {
    print(paste0("The ",i,"th simulation."))
  print(error_metrics(tail(vanilla_FR[[i]],last_len), tail(b_ou_FR$case_true[1:ind[i]],last_len)))
  print(error_metrics(tail(withGT_FR[[i]],last_len), tail(b_ou_FR$case_true[1:ind[i]],last_len)))
  vanilla_FR_combined_last[[i]] <- as.data.frame(error_metrics(tail(vanilla_FR[[i]],last_len), tail(b_ou_FR$case_true[1:ind[i]],last_len)))
  withGT_FR_combined_last[[i]] <- as.data.frame(error_metrics(tail(withGT_FR[[i]],last_len), tail(b_ou_FR$case_true[1:ind[i]],last_len)))
}

mean_vanilla_FR_combined_last <- Reduce(`+`, vanilla_FR_combined_last) / length(vanilla_FR_combined_last)
mean_withGT_FR_combined_last <- Reduce(`+`, withGT_FR_combined_last) / length(withGT_FR_combined_last)

mean_vanilla_FR_combined_last
mean_withGT_FR_combined_last
```

```{r}
test_num <- 1

# GT
y_true_FR <- b_ou_FR$case_true[1:ind[test_num]]

y_rep_mat_FR <- test_FR[[test_num]]$draws(variables = "N", format = "draws_matrix")
pred_mat_FR <- t(y_rep_mat_FR)

crps_vec_FR  <- crps_sample(y   = y_true_FR,  
                         dat = pred_mat_FR)
mean_crps_FR <- mean(crps_vec_FR)

#
y_rep_mat_GT_FR <- test_GT_FR[[test_num]]$draws(variables = "N", format = "draws_matrix")
pred_mat_GT_FR <- t(y_rep_mat_GT_FR)

crps_vec_GT_FR  <- crps_sample(y   = y_true_FR,  
                         dat = pred_mat_GT_FR)
mean_crps_GT_FR <- mean(crps_vec_GT_FR)

mean_crps_FR
mean_crps_GT_FR
```

```{r}


# GT
y_true_FR_l <- tail(b_ou_FR$case_true[1:ind[test_num]], last_len)

y_rep_mat_FR <- test_FR[[test_num]]$draws(variables = "N", format = "draws_matrix")
pred_mat_FR_l <- tail(t(y_rep_mat_FR), last_len)

crps_vec_FR_l  <- crps_sample(y   = y_true_FR_l,  
                         dat = pred_mat_FR_l)
mean_crps_FR_l <- mean(crps_vec_FR_l)

#
y_rep_mat_GT_FR <- test_GT_FR[[test_num]]$draws(variables = "N", format = "draws_matrix")
pred_mat_GT_FR_l <- tail(t(y_rep_mat_GT_FR), last_len) 

crps_vec_GT_FR_l  <- crps_sample(y   = y_true_FR_l,  
                         dat = pred_mat_GT_FR_l)
mean_crps_GT_FR_l <- mean(crps_vec_GT_FR_l)

mean_crps_FR_l
mean_crps_GT_FR_l
```


```{r}
mcmc_areas(test_FR[[test_num]]$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_FR[[test_num]]$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_FR[[test_num]]$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_FR[[test_num]]$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_FR[[test_num]]$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_FR[[test_num]]$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true = tibble(
    parameter = grep("^b\\[.+\\]$", varnames_FR[[test_num]], value = TRUE),
    x = b_ou_FR$b[1:ind[test_num]]
)
mcmc_areas(test_FR[[test_num]]$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^phi\\[.+\\]$", varnames_FR[[test_num]], value = TRUE),
    x =  b_ou_FR$phi[1:ind[test_num]]
)
mcmc_areas(test_FR[[test_num]]$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames_FR[[test_num]], value = TRUE),
    x = b_ou_FR$q[10,]
)
mcmc_areas(test_FR[[test_num]]$draws(grep("^q\\[10,.+\\]$", varnames_FR[[test_num]], value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames_FR[[test_num]], value = TRUE),
    x = b_ou_FR$lambda[1:ind[test_num]]
)
mcmc_areas(test_FR[[test_num]]$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames_FR[[test_num]], value = TRUE),
    x = b_ou_FR$case_true[1:ind[test_num], 1]
)
mcmc_areas(test_FR[[test_num]]$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)
```

```{r}
mcmc_areas(test_GT_FR[[test_num]]$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_GT_FR[[test_num]]$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_GT_FR[[test_num]]$draws("sigma_epsilon"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_GT_FR[[test_num]]$draws("beta0"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("beta_x"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test_GT_FR[[test_num]]$draws("rho_w"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test_GT_FR[[test_num]]$draws("sigma_w"), prob = 0.95, prob_outer = 0.95)

param_true = tibble(
    parameter = grep("^b\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = b_ou_FR$b[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^phi\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x =  b_ou_FR$phi[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = b_ou_FR$q[10,]
)
mcmc_areas(test_GT_FR[[test_num]]$draws(grep("^q\\[10,.+\\]$", varnames_GT_FR[[test_num]], value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^beta_s\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = beta_s
)
mcmc_areas(test_GT_FR[[test_num]]$draws("beta_s"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^season\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = s_t[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("season"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^beta_s\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = beta_s
)
mcmc_areas(test_GT_FR[[test_num]]$draws("beta_s"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^w\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = w_t[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("w"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^epsilon\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = epsilon_t[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("epsilon"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = b_ou_FR$lambda[1:ind[test_num]]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
    x = b_ou_FR$case_true[1:ind[test_num], 1]
)
mcmc_areas(test_GT_FR[[test_num]]$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

```

```{r}
library(posterior)   # for mcmc_areas
library(ggplot2)
library(patchwork)

# 1. β_x
param_true_x <- tibble(
  parameter = grep("^beta_x\\[.+\\]$", varnames_GT[[test_num]], value = TRUE),
  x         = beta1[1:ind[test_num]]
)
p1 <- mcmc_areas(test_GT[[test_num]]$draws("beta_x"), prob_outer = 0.95) +
  geom_point(data = param_true_x, aes(x = x), color = "red", size = 1) +
  ggtitle("β_x")

# 2. season
param_true_s <- tibble(
  parameter = grep("^season\\[.+\\]$", varnames_GT[[test_num]], value = TRUE),
  x         = s_t[1:ind[test_num]]
)
p2 <- mcmc_areas(test_GT[[test_num]]$draws("season"), prob_outer = 0.95) +
  geom_point(data = param_true_s, aes(x = x), color = "red", size = 1) +
  ggtitle("season")

# 3. β_s
param_true_bs <- tibble(
  parameter = grep("^beta_s\\[.+\\]$", varnames_GT[[test_num]], value = TRUE),
  x         = beta_s
)
p3 <- mcmc_areas(test_GT[[test_num]]$draws("beta_s"), prob_outer = 0.95) +
  geom_point(data = param_true_bs, aes(x = x), color = "red", size = 1) +
  ggtitle("β_s")

# 4. η
param_true_eta <- tibble(
  parameter = grep("^eta\\[.+\\]$", varnames_GT[[test_num]], value = TRUE),
  x         = eta[1:ind[test_num]]
)
p4 <- mcmc_areas(test_GT[[test_num]]$draws("eta"), prob_outer = 0.95) +
  geom_point(data = param_true_eta, aes(x = x), color = "red", size = 1) +
  ggtitle("η")

# 拼成 2×2
(p1 | p2) /
(p3 | p4) 

```

```{r}
library(posterior)   # for mcmc_areas
library(ggplot2)
library(patchwork)

# 1. β_x
param_true_x <- tibble(
  parameter = grep("^beta_x\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
  x         = beta1[1:ind[test_num]]
)
p1 <- mcmc_areas(test_GT_FR[[test_num]]$draws("beta_x"), prob_outer = 0.95) +
  geom_point(data = param_true_x, aes(x = x), color = "red", size = 1) +
  ggtitle("β_x")

# 2. season
param_true_s <- tibble(
  parameter = grep("^season\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
  x         = s_t[1:ind[test_num]]
)
p2 <- mcmc_areas(test_GT_FR[[test_num]]$draws("season"), prob_outer = 0.95) +
  geom_point(data = param_true_s, aes(x = x), color = "red", size = 1) +
  ggtitle("season")

# 3. β_s
param_true_bs <- tibble(
  parameter = grep("^beta_s\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
  x         = beta_s
)
p3 <- mcmc_areas(test_GT_FR[[test_num]]$draws("beta_s"), prob_outer = 0.95) +
  geom_point(data = param_true_bs, aes(x = x), color = "red", size = 1) +
  ggtitle("β_s")

# 4. η
param_true_eta <- tibble(
  parameter = grep("^eta\\[.+\\]$", varnames_GT_FR[[test_num]], value = TRUE),
  x         = eta[1:ind[test_num]]
)
p4 <- mcmc_areas(test_GT_FR[[test_num]]$draws("eta"), prob_outer = 0.95) +
  geom_point(data = param_true_eta, aes(x = x), color = "red", size = 1) +
  ggtitle("η")

# 拼成 2×2
(p1 | p2) /
(p3 | p4) 

```

